Update Lesson_4_Let_Users_Vote_On_Proposals.md
buildspace/buildspace-projects pull request #1019
Opened 2022-03-31 23:33 UTC by captainrandom

When copying your code from the buildspace-dao-final repo to support the (against / abstain / for) form + voting calls, you reference the zero address variable, but there is no callout to add the corresponding import. See error message below:

failed to delegate tokens ReferenceError: AddressZero is not defined
    at onSubmit

This import should fix the issue.

2022-04-01 01:06 UTC, nachoiacovino requested changes

2022-04-01 01:06 UTC, nachoiacovino commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +Add the zero address import after your exising imports:
Can you add it before the line of "Go ahead and replace..." ?

2022-04-08 04:50 UTC, captainrandom commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +Add the zero address import after your exising imports:
This has been fixed.

2022-04-29 00:03 UTC, AlmostEfficient approved these changes

2022-04-29 00:03 UTC, merged

2022-04-29 00:03 UTC, AlmostEfficient commented
Thank you!