Fixed/alvaroeds
buildspace/buildspace-projects pull request #1054
Opened 2022-04-28 18:09 UTC by alvaroeds

Hello, I found this error in a function when following the steps to create an nft in solana. I also found a broken URL in the main readme.

2022-05-10 13:55 UTC, adilanchian requested changes
Thanks so much for the changes here!

Asking Raza to check this out for me real quick :)!


Thanks!

2022-05-10 13:55 UTC, adilanchian commented on .all-contributorsrc
> +      ]
you don't need to add this :). Bot will do all of this

Please remove!

2022-05-10 13:55 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_1_Call_Candy_Machine_From_App.md
> +
@AlmostEfficient can I get a second pair of eyes on this please :)?

2022-05-13 16:13 UTC, alvaroeds commented on .all-contributorsrc
> +      ]
@adilanchian  Ready! I just deleted those changes :D

2022-09-23 01:16 UTC, helloitsm3 commented
Content is outdated. We've already migrated to the new Sugar CLI

2022-09-23 05:19 UTC, closed without merging