Added NFT process to all projects
buildspace/buildspace-projects pull request #1269
Opened 2022-09-14 13:04 UTC by helloitsm3

2022-09-14 14:06 UTC, adilanchian requested changes
I just added changes to the first project that can be replicated for every project please!

2022-09-14 14:06 UTC, adilanchian commented on Flow_NFTs/en/Section_0/Lesson_1_Welcome_To_Flow.md
> +**Note: If you did not receive your NFT after 7 days, please reach out to either Raza or Alec on Discord!**
Can you drop our Discord IDs here please :)?

2022-09-14 14:06 UTC, adilanchian commented on Flow_NFTs/en/Section_0/Lesson_1_Welcome_To_Flow.md
> +BTW -- if you want to make a tweet telling the world that you're building an app with Flow today and tag @\_buildspace, go for it!
typo?

2022-09-14 14:06 UTC, adilanchian commented on Flow_NFTs/en/Section_0/Lesson_1_Welcome_To_Flow.md
> +**You'll only be eligible for the NFT if you finish it within 60 days of signing up, if not, you'll not be able to obtain an NFT!** So make sure you schedule time to finish, you got this!
Can we change this to - 

"You'll only be eligible for the NFT if you finish it within 60 days of signing up. "

**Note: It can take up to 7 days for your NFT to arrive (you'll get an email also!). If it's been more than 7 days please reach out to either Raza or Alec on Discord!**

2022-09-14 14:06 UTC, adilanchian commented on Flow_NFTs/en/Section_0/Lesson_1_Welcome_To_Flow.md
> +**Note: If you did not receive your NFT after 7 days, please reach out to either Raza or Alec on Discord!**
lil copy change
**Note: It can take up to 7 days for your NFT to arrive (you'll get an email also!). If it's been more than 7 days please reach out to either Raza or Alec on Discord!**

2022-09-14 14:13 UTC, helloitsm3 commented on Flow_NFTs/en/Section_0/Lesson_1_Welcome_To_Flow.md
> +BTW -- if you want to make a tweet telling the world that you're building an app with Flow today and tag @\_buildspace, go for it!
Not a typo. This is automatically added due to  prettier but doesn't affect what's being rendered. It'll still render as `@buildspace`

2022-09-14 15:24 UTC, adilanchian requested changes
Almost there! Looks like you may have some weird stuff with formatting

2022-09-14 15:24 UTC, adilanchian commented on JS_DAO/en/Section_0/Lesson_1_Lets_Build_Some_Cool_Shit.md
> +**Note: Each cohort is named after a star (ex. [Alkes](https://www.star-facts.com/alkes/), [Beid](https://www.universeguide.com/star/19587/beid), etc)! Also, the # on the back will be the # minted wh
Can you remove this text about the star names? Not a thing we are doing anymore haha

2022-09-14 15:24 UTC, adilanchian commented on JS_DAO/en/Section_0/Lesson_1_Lets_Build_Some_Cool_Shit.md
> +**BTW -- if you want to make a tweet telling the world that you're building your own DAO today and tag [@\_buildspace](https://twitter.com/_buildspace)! I always say this, but 1) that tweet could ins
Got another forward slash here?

Looks like your formatting may be doing some weird stuff here

2022-09-14 15:24 UTC, adilanchian commented on NFT_Collection/en/Section_0/Lesson_1_What_Are_We_Building.md
> +**Note: instead of "Alkes", your NFT would say the name of your cohort — each cohort is named after a star! Also, the # at the bottom right will be the # minted which depends on when you claim the NF
Remove star name text here please

2022-09-14 15:24 UTC, adilanchian commented on NFT_Game/en/Section_0/Lesson_1_What_Are_We_Building.md
> +**Note: Each cohort is named after a star! Also, the # at the bottom right will be the # minted which depends on when you finish! It can take up to 7 days for your NFT to arrive (you'll get an email
Remove start name plz

2022-09-14 15:24 UTC, adilanchian commented on Polygon_ENS/en/Section_0/Lesson_1_Lets_Make_Some_Domains.md
> +-   **some react.js**
Formatting revert please

2022-09-14 15:24 UTC, adilanchian commented on Polygon_ENS/en/Section_0/Lesson_1_Lets_Make_Some_Domains.md
> +**BTW -- if you want to make a tweet telling the world that you're building your own ENS today and tag [@\_buildspace](https://twitter.com/_buildspace), go for it!**
Remove slash

2022-09-14 15:24 UTC, adilanchian commented on Solana_NFTs/en/Section_0/Lesson_1_Lets_Ship_Some_NFTs.md
> +**Note: Each cohort is named after a star (ex. [Alkes](https://www.star-facts.com/alkes/), [Beid](https://www.universeguide.com/star/19587/beid), etc)! Also, the # at the bottom will be the # minted
Remove star names

2022-09-14 15:24 UTC, adilanchian commented on Solana_Pay_Store/en/Section_0/Lesson_1_What_Are_We_building.md
> +BTW -- if you want to make a tweet telling the world that you're building an app with Solana Pay today and tag @\_buildspace, go for it!
remove slash

2022-09-14 15:24 UTC, adilanchian commented on Solidity_And_Smart_Contracts/en/Section_0/Lesson_1_Welcome.md
> +**Note: instead of "Capella", yours would say name of your cohort — each cohort is named after a star! Also, the # at the bottom right will be the # minted which depends on when you claim the NFT. It
Remove star name text

2022-09-14 15:30 UTC, helloitsm3 commented on JS_DAO/en/Section_0/Lesson_1_Lets_Build_Some_Cool_Shit.md
> +**BTW -- if you want to make a tweet telling the world that you're building your own DAO today and tag [@\_buildspace](https://twitter.com/_buildspace)! I always say this, but 1) that tweet could ins
Forward slash is done automatically by prettier but it doesn't affect the rendering. Do you still want me to remove it?

2022-09-16 09:47 UTC, AlmostEfficient approved these changes

2022-09-17 01:54 UTC, AlmostEfficient approved these changes

2022-09-17 01:54 UTC, merged