Update Lesson_6_Give_Your_Token_Identity.md
buildspace/buildspace-projects pull request #1367
Opened 2022-11-14 08:51 UTC by shungo0222

I fixed some typos and code.

`await findMetadataPda(mint)` -> `metaplex.nfts().pdas().metadata({mint})`
Because `findMetadataPda` is deprecated.

2022-11-15 10:18 UTC, AlmostEfficient requested changes

2022-11-15 10:18 UTC, AlmostEfficient commented on Solana_Core/en/Core_2/Lesson_6_Give_Your_Token_Identity.md
>  } from "@metaplex-foundation/js"
Why remove `findMetadataPda`?

2022-11-15 10:18 UTC, AlmostEfficient commented on Solana_Core/en/Core_2/Lesson_6_Give_Your_Token_Identity.md
> +  const metadataPDA = metaplex.nfts().pdas().metadata({mint})
I'm confused

2022-11-15 10:37 UTC, shungo0222 commented on Solana_Core/en/Core_2/Lesson_6_Give_Your_Token_Identity.md
> +  const metadataPDA = metaplex.nfts().pdas().metadata({mint})
I replied below.

2022-11-17 00:16 UTC, AlmostEfficient approved these changes

2022-11-17 00:16 UTC, merged

2022-11-17 00:16 UTC, AlmostEfficient commented
Ooof Metaplex team going at the speed of light again