Mentioned NFT-Preview tool
buildspace/buildspace-projects pull request #186
Opened 2021-10-19 16:06 UTC by Utkarshbhimte

I built this tool to make it easy for me to get a quick preview of the `tokenURI` content and the image.

2021-10-31 20:34 UTC, Utkarshbhimte commented
Hey @adilanchian, sure. I will add some more content.

Not sure how it can be important, it's just there to make it easier to experiment with different designs and debug randomly generated text content and also a quick check if the `tokenURI` data is valid or not (all those manual string concatenation are bug-prone and painful to debug)

2021-11-01 14:05 UTC, adilanchian commented
Ya sorry I should have been a bit more specific about this - 

This section just feels a bit out of place. Like why do I need to debug my `tokenURI`? So something along the lines of:

"Now that you have your `tokenURI` setup, how do we know if it's actually correct? After all, this holds all our data for our NFT! You can use a cool tool like - {insert tool} to see exactly what data this thing is holding."

You see what I mean? Let me know and I can write it up if you want :)

2021-11-02 10:31 UTC, Utkarshbhimte commented
Thanks for that @adilanchian, I have made some changes there. 

Writing is not my strong suit but I appreciate all the help. 😊

2021-11-02 13:50 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_3_Dynamically_Generating_NFTs.md
> +![](https://imgur.com/a/cfZiWh8)
Hmm I don't see an image preview here when looking at the non-raw version of the markdown! Can you verify this for me?

Thanks!

2021-11-02 13:50 UTC, adilanchian requested changes
Yessss looks great!

I see that you added an image here, but it doesn't seem to render for me? Can you verify that this is looking okay?

2021-11-02 13:53 UTC, Utkarshbhimte commented
Will check and share soon [image: 😊]

Regards
Utkarsh Bhimte

On Tue, Nov 2 2021 at 7:21 PM, Utkarsh Bhimte ***@***.***>
wrote:

> The imgur link in the last line
>
> Regards
> Utkarsh Bhimte
>
> On Tue, Nov 2 2021 at 7:20 PM, Alec Dilanchian ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In NFT_Collection/en/Section_2/Lesson_3_Dynamically_Generating_NFTs.md
>> <https://github.com/buildspace/buildspace-projects/pull/186#discussion_r741074686>
>> :
>>
>> > +    string memory finalTokenUri = string(
>> +        abi.encodePacked("data:application/json;base64,", json)
>> +    );
>> +
>> +    console.log("\n--------------------");
>> +    console.log(
>> +        string(
>> +            abi.encodePacked(
>> +                "https://nftpreview.0xdev.codes/?code=",
>> +                finalTokenUri
>> +            )
>> +        )
>> +    );
>> +    console.log("--------------------\n");
>> +```
>> +![](https://imgur.com/a/cfZiWh8)
>>
>> Hmm I don't see an image preview here when looking at the non-raw version
>> of the markdown! Can you verify this for me?
>>
>> Thanks!
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/buildspace/buildspace-projects/pull/186#pullrequestreview-795356639>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADGCRPOHO63WJ63NDXABZPDUJ73CRANCNFSM5GJQ7YNA>
>> .
>>
>

2021-11-02 13:57 UTC, adilanchian commented
Awesome :)

Ya just for clarity this it what GitHub is showing me:

![image](https://user-images.githubusercontent.com/13204620/139861325-07a50a79-6891-4976-986c-42511f30f9ba.png)


^ looking at this I think you for got to add `[image]` in the bracket!

2021-11-03 14:10 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_3_Dynamically_Generating_NFTs.md
> +![](https://imgur.com/a/cfZiWh8)
Looks like here you just need to put: 

`![image](https://imgur.com/a/cfZiWh8)`

2021-11-03 14:13 UTC, Utkarshbhimte commented on NFT_Collection/en/Section_2/Lesson_3_Dynamically_Generating_NFTs.md
> +![](https://imgur.com/a/cfZiWh8)
done

2021-11-03 14:18 UTC, adilanchian requested changes

2021-11-03 14:18 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_3_Dynamically_Generating_NFTs.md
> +![image](https://imgur.com/a/cfZiWh8)
Hehe this is still slightly broken :)

You need to get the Image Address which is actually - `https://i.imgur.com/CsBxROj.png`

2021-11-03 14:28 UTC, adilanchian requested changes

2021-11-03 14:28 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_3_Dynamically_Generating_NFTs.md
> +```
Hey sorry one more thing here - 

Looks like you have an extra tab on every line here can you remove those please :)?

2021-11-03 18:16 UTC, Utkarshbhimte commented
Done 😊

2021-11-04 15:07 UTC, adilanchian commented
WOWZA. It's time. Very nice work and thanks for the contribution!

2021-11-04 15:07 UTC, merged

2021-11-04 15:07 UTC, adilanchian commented
@all-contributors please add @Utkarshbhimte  for doc

2021-11-04 15:17 UTC, Utkarshbhimte commented
Thanks @adilanchian , I am planning to make it better and add all the opensea attributes here.
Make it a full-fletched opensea preview. 😊