added verify contract for etherscan for nft-collection
buildspace/buildspace-projects pull request #285
Opened 2021-11-01 02:16 UTC by chee-chyuan

adding steps to verify contract for etherscan for nft-collection
i will seperately pr for the nft-game after this pr is merged

2021-11-01 15:08 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +📝Verify contract on Etherscan
Can you add a period at the end of this please :)?

2021-11-01 15:12 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +
Can you tweak this a bit - 

However bytecodes aren't really readable, but Etherscan has the magic to 'convert' them to something more user friendly. For that magic to work, Etherscan will need your help.

2021-11-01 15:13 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +Notice that there is a prompt that requests us to <b>Verify and Publish</b> our contract source code. If we follow the link, we are required to manually select our contract settings and paste our cod
Can you change `<b>Verify and Publish</b>` to use asterisks please `**Verify and Publish**`

2021-11-01 15:14 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +//rest of the code
Can you tweak `//rest of code` to be `// Rest of code`

2021-11-01 15:14 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +.......
Can you change this to `...` please?

2021-11-01 15:15 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +  ....,
Can you change this to:

`// Rest of the config`

`...`

2021-11-01 15:15 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +
Remove this space please :)

2021-11-01 15:15 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +
Remove this space please :)

2021-11-01 15:16 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +Not quite done yet. Those with keen eyes will notice that Etherscan requires an ApiKey.
Can you change this to say - 

We are almost there! You may have noticed that the `etherscan` object in our config requires an `apiKey`! This means you will need an account with Etherscan to get this key.

2021-11-01 15:19 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +If you don't have an account already, head to etherscan.io to create a free user account. After which head to your profile settings and under `API-KEYs` create a new apikey
Can you change this to include the etherscan.io signup link?

2021-11-01 15:20 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +After which, add your api key to the etherscan apikey property in our `hardhat.config.js` similarly we will be using `.env` later on for this.
Can you tweak this to say - 

Sweet you got your API key. Time to head back to your `hardhat.config.js` file and change the `apiKey` property to be your newly generated key.

2021-11-01 15:22 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +
I don't think we actually need this part :). Can you remove please?

2021-11-01 15:57 UTC, chee-chyuan commented
> Hey @chee-chyuan !
> 
> This is an AWESOME addition to this project. I actually learned some new stuff here myself haha. I do think this should actually live [in this section](https://github.com/buildspace/buildspace-projects/blob/main/NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md#-change-up-our-contract-deploy)
> 
> It can be an "extra" instead of a requirement for the project if this makes sense!

Sure thing. I have moved it over to the end of Section 2: lesson 2. and have added the word `Something Extra:` lmk if you would like them removed

2021-11-01 15:58 UTC, chee-chyuan commented
> Alrighty -
> 
> I left a solid amount of changes here! Overall, your content is great! I just wanted to change a few things up here :)
> 
> Let me know if you have any questions or concerns!

wow thanks! i appreciate your feedback. yours feel much more natural. have edited based on your feedbacks

2021-11-02 14:12 UTC, adilanchian requested changes
Yessss we are getting there!! You're doing awesome :).

Going to tag @farzaa to get a second pair of eyes on this as well!

2021-11-02 14:12 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +
I think here we might want to start with something like:

**Note: This section is totally optional, but is a really cool part about Etherscan that you should understand.**

If you select the **Contract** tab in Etherscan, you will notice a long list of text characters that starts from `0x608060405234801...` Hmm.. what could that be 🤔 ?

2021-11-02 14:12 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +
Can you change `[This is also a cool article](https://ethervm.io/) about EVM opcodes` to - 

[This is also a cool article](https://ethervm.io/) about EVM opcodes by the way 🤘.

2021-11-02 14:12 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +
Can you change this to - 

So, we know that bytecodes aren't readable to us. We want to be able to see the code we wrote right in Etherscan. Luckily, Etherscan has the magic to help us do that!

2021-11-02 14:12 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +If you don't have an account already, head to https://etherscan.io/register to create a free user account. After which head to your profile settings and under `API-KEYs` create a new apikey
Can you change `https://etherscan.io/register` to `[https://etherscan.io/register](https://etherscan.io/register)` please :)

2021-11-02 14:12 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +Your constuctor arguments will simply be inital `_totalSupply` which you have set in your `run.js` script.
I think for this we can just put everything in the command like so:

`npx hardhat verify YOUR_CONTRACT_ADDRESS --network rinkeby _totalSupply`

2021-11-02 14:57 UTC, chee-chyuan commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +
gotcha let me quicky add that in too

2021-11-02 15:08 UTC, chee-chyuan commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +Your constuctor arguments will simply be inital `_totalSupply` which you have set in your `run.js` script.
i was afraid it might not be obvious but i guess we can try first

2021-11-02 15:10 UTC, chee-chyuan commented
thanks again. much cleaner now. im not really good in writing

2021-11-03 14:14 UTC, adilanchian approved these changes
Looks good to me! Thanks for working with me on making these changes :)

I think @farzaa wanted a few changes so will let him chime in to give approval as well

2021-11-03 15:14 UTC, chee-chyuan commented
> Looks good to me! Thanks for working with me on making these changes :)
> 
> I think @farzaa wanted a few changes so will let him chime in to give approval as well

lovely! just let me know of how i could make it better

2021-11-04 15:08 UTC, adilanchian commented
Thanks @chee-chyuan - will do!

2021-11-04 15:19 UTC, farzaa commented
Hey @chee-chyuan I thinki this should be in "finishing touches" under the github section. Would be a perfect fit there.

https://github.com/buildspace/buildspace-projects/blob/main/NFT_Collection/en/Section_4/Lesson_2_Ship_It.md

Also -- maybe at the top you can sorta explain why verifying is contract is cool and maybe link an example to one!! Showing off how you can hit the functions right in Etherscan -- and how magical that is!!! It's a cool feeling. Very different from github where you're required to pull the code down. Maybe even compare github to ethereum/etherscan. 

You want to motivate the user just a bit more to care!!!

2021-11-04 15:22 UTC, Utkarshbhimte commented
when I was doing this, It wasn't working till I removed all the console.logs, I think that is a useful side note to add. 
It gave me a lot of pain 😅

also adding to @farzaa's point, it is more essential to verify the contracts so you can ask for help easily in the community. Asking for help made it super simple when they were able to see what my code was clearly.

2021-11-04 15:40 UTC, chee-chyuan commented
> when I was doing this, It wasn't working till I removed all the console.logs, I think that is a useful side note to add. It gave me a lot of pain 😅
> 
> also adding to @farzaa's point, it is more essential to verify the contracts so you can ask for help easily in the community. Asking for help made it super simple when they were able to see what my code was clearly.

there shouldnt be a problem with console.log. in fact here is an example which i used with console.log https://rinkeby.etherscan.io/address/0x902ebbecafc54f7a8013a9d7954e7355309b50e6#code (refer file 5 of 14)

2021-11-05 10:18 UTC, chee-chyuan commented
hey @farzaa I have moved over the Verify Etherscan to the section 4 lesson 2. let me know if its good. also added some motivation which i think why its cool to verify contracts on Etherscan. my explanation will probably not be the best and do let me know if I can do anything to make it better.

Cheers

2021-11-05 15:26 UTC, adilanchian requested changes
Looking good on my end after these changes!

2021-11-05 15:26 UTC, adilanchian commented on NFT_Collection/en/Section_2/Lesson_2_Minting_NFTs_With_Static_SVGs.md
> +
Can you remove this new line please :)

2021-11-05 15:26 UTC, adilanchian commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +```
Can you change this to ```javascript please?

2021-11-08 15:05 UTC, adilanchian commented
This is an insanely epic pr. Thanks again for making this! We are good to go woot woot!

2021-11-08 15:05 UTC, merged

2021-11-08 15:05 UTC, adilanchian commented
@all-contributors please add @chee-chyuan for doc

2021-11-08 15:54 UTC, chee-chyuan commented
> This is an insanely epic pr. Thanks again for making this! We are good to go woot woot!

what you guys are doing are way more epic!!! thanks for making buildspace happen. i only try to help out on the little stuff wherever i can. i will create a similar pr to add this feature into the nft game course