Update_on_provider_change
buildspace/buildspace-projects pull request #331
Opened 2021-11-07 06:26 UTC by NickGonzalez04

- To change the provider being set with a defined 'provider' variable. Didn't explain why it needed to be a variable after updating our code.

2021-11-08 19:09 UTC, adilanchian requested changes
Good catch!

Left one small comment here :). Thanks!

2021-11-08 19:09 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Lesson_3_Store_Basic_Data.md
> +	// Create and set the provider. We set it before but we needed to update it, so that it can communicate with our frontend!
It looks like the indentation on this is a tad off!

Can you fix for me please :)?

2021-11-09 15:07 UTC, NickGonzalez04 commented on Solana_And_Web3/en/Section_2/Lesson_3_Store_Basic_Data.md
> +	// Create and set the provider. We set it before but we needed to update it, so that it can communicate with our frontend!
Done! :0

2021-11-10 00:11 UTC, adilanchian commented
POGGG thank you :)

2021-11-10 00:11 UTC, merged