Added step on how to generate local keypair
buildspace/buildspace-projects pull request #374
Opened 2021-11-12 09:54 UTC by tapabratadey

Also added some explanation to the step

2021-11-12 12:35 UTC, adilanchian requested changes
Left some notes :)

Thanks!

2021-11-12 12:35 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +
Can you remove this new line please?

2021-11-12 12:35 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +Next thing we need to do is actually generate a local Solana wallet to work with. Don't worry about create a passphrase for now, just tap "Enter" when it asks.
Minor grammar - 

"Don't worry about creating a passphrase for now, just press "Enter" when asked!"

2021-11-12 12:35 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +```
Can we add a new line here please?

2021-11-12 12:35 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This will generate a new keypair (which is sorta like our local wallet we'll use to talk to our programs via the command line) to `target/deploy/myepicproject-keypair.json`. If you run `solana config
I think this should say something like  - 

This will generate a new keypair, which we will use to talk to our Solana programs! You will see this keypair in a generated `JSON` file located at `target/deploy/myepicproject-keypair.json`. 

I don't think we need this line `If you run `solana config get` you'll see something called `Keypair Path` with the path `target/deploy/myepicproject-keypair.json`, that's where the wallet has been created, feel free to check it out!`

As you pretty much just said that :)

2021-11-12 21:19 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +
Removed new line on line 201 ✅

2021-11-12 21:19 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +Next thing we need to do is actually generate a local Solana wallet to work with. Don't worry about create a passphrase for now, just tap "Enter" when it asks.
Updated grammar changes on line 202

2021-11-12 21:20 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +```
Added a new line after line 207

2021-11-12 21:20 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This will generate a new keypair (which is sorta like our local wallet we'll use to talk to our programs via the command line) to `target/deploy/myepicproject-keypair.json`. If you run `solana config
Updated description

2021-11-12 21:25 UTC, tapabratadey reviewed
Thanks for the detailed feedback on the PR. Resolved changes requested.

2021-11-13 12:57 UTC, adilanchian requested changes
Thanks for the tweaks!

As I read over this again, I felt like there were a couple things that needed to be changed. Let me know your thoughts !

Thanks again :)

2021-11-13 12:57 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +Don't worry about creating a passphrase for now, just press "Enter" when asked!
So reading this over again I feel like we need a tad bit more explanation of what this local keypair is going to be used for. 

Can you add like one sentence before here that talks about why this is here?

2021-11-13 12:57 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +Don't worry about creating a passphrase for now, just press "Enter" when asked!
Then, we can also lead into this idea of running the command - 

"In order to create this keypair let's go ahead and run this command in our terminal:"

2021-11-13 12:57 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This will generate a new keypair, which we will use to talk to our Solana programs! You will see this keypair in a generated `JSON` file located at `target/deploy/myepicproject-keypair.json`.
Ya so maybe this moves to the first comment I made? Whatever you think would fit here?

2021-11-13 15:56 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +Don't worry about creating a passphrase for now, just press "Enter" when asked!
Tweaked changes on #391

2021-11-13 15:56 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This will generate a new keypair, which we will use to talk to our Solana programs! You will see this keypair in a generated `JSON` file located at `target/deploy/myepicproject-keypair.json`.
Tweaked changes on #391

2021-11-13 15:58 UTC, tapabratadey commented
Thanks for the feedback! I added a bit more explanation on why we need to create the local keypair.

I messed up the forked project so I tweaked changes on a new PR on #391. Apologies for any inconvenience 😅

2021-11-13 15:59 UTC, closed without merging