Minor grammatical corrections/suggestions
buildspace/buildspace-projects pull request #384
Opened 2021-11-13 04:32 UTC by 0xandreharrison

2021-11-13 13:14 UTC, adilanchian commented on Solana_And_Web3/en/Section_4/Lesson_1_Finishing_Touches_Web_App_And_Program.md
> +Who need Stripe and PayPal when you have a super low-gas fee blockchain that lets you make instant payments?!?
Small typo here as well - 

"Who needs Stripe and PayPal when you have a super low, gas fee blockchain that lets you make instant payments?!?

2021-11-13 13:14 UTC, adilanchian requested changes
One minor tweak please :)

2021-11-17 14:16 UTC, adilanchian commented
Sup @0xandreharrison !

Just checking in :)

2021-11-18 18:19 UTC, adilanchian commented on Solana_And_Web3/en/Section_4/Lesson_1_Finishing_Touches_Web_App_And_Program.md
> +Who need Stripe and PayPal when you have a super low-gas fee blockchain that lets you make instant payments?!?
I went ahead and resolved this :)

2021-11-18 18:19 UTC, merged

2021-11-19 04:33 UTC, 0xandreharrison commented
Sup @adilanchian! I'll see you at the next Solana NFT collection project :)

2021-11-19 04:39 UTC, 0xandreharrison commented
I hope you weren't waiting for me! If so, I'm sorry not too familiar with how all the processes work ;)