Update `m1_setup.md`
buildspace/buildspace-projects pull request #391
Opened 2021-11-13 15:55 UTC by tapabratadey

Resolving changes requested in #374 on how to generate a local keypair. Apologies for opening another PR.

2021-11-14 17:01 UTC, adilanchian requested changes
Hey - 

Thanks so much for this! Just one more change hehe. Sorry! 

Also - you don't need to create PRs here, you can just update this branch with your changes :)

2021-11-14 17:01 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +In order to talk to our Solana programs, let us generate a new keypair! We can run this command in our terminal:
Can you change this to - 

In order to talk to our Solana programs, let's generate a new keypair! We can run this command in our terminal:

2021-11-15 08:09 UTC, tapabratadey reviewed
Thanks again!! Next time will make sure not to open a PR on a change request :p

2021-11-15 17:40 UTC, adilanchian requested changes
Sorry - just one more change here!!

2021-11-15 17:40 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +In order to talk to our Solana programs, let's generate a new keypair! We can run this command in our terminal:
I think we need just a tad bit more explanation here. Some like - 

In order for us to talk to our Solana programs we need to generate a keypair. Really all you need to know about this is it allows us to sign for transactions in Solana! Still curious? [Take a look at this page](https://solana-labs.github.io/solana-web3.js/classes/Keypair.html) for more information 

Let me know what you think!

2021-11-15 21:23 UTC, tapabratadey reviewed
Added description to  `Create a local keypair`. Thanks again!

2021-11-15 21:23 UTC, tapabratadey commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +In order to talk to our Solana programs, let's generate a new keypair! We can run this command in our terminal:
Made the changes! Super nice documentation. Thanks for sharing!

2021-11-17 14:18 UTC, adilanchian approved these changes

2021-11-17 14:18 UTC, adilanchian commented
@tapabratadey LOOKING GOOD!

Thanks so much for taking the time to add this :). It is indeed epic 🤘

2021-11-17 14:18 UTC, merged

2021-11-17 14:19 UTC, adilanchian commented
@all-contributors please add @tapabratadey for doc