Update Lesson_1_Get_Local_Solana_Env_Running.md
buildspace/buildspace-projects pull request #392
Opened 2021-11-13 17:04 UTC by chiarawilden

A few typos – "it;d" actually got copied and pasted in here while I was searching the doc – will update

2021-11-14 17:03 UTC, adilanchian requested changes
Thanks for this!!

Small type change here please :)

2021-11-14 17:03 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Lesson_1_Get_Local_Solana_Env_Running.md
> +Next thing you'll want to do is run these two commands separately:it;d
Looks like a bad copy paste here - `it;d`

2021-11-15 16:22 UTC, chiarawilden commented
@adilanchian I think this should fix it – still a little confused by how editing pull requests works.

2021-11-15 17:41 UTC, adilanchian commented
You did great @chiarawilden !!

Feel free to DM me in Discord whenever if you have any questions about this stuff, but for now - NICE WORK AND THANK YOU <3

2021-11-15 17:42 UTC, merged

2021-11-15 17:42 UTC, adilanchian commented
@all-contributors please add @chiarawilden  for doc