address typos
buildspace/buildspace-projects pull request #402
Opened 2021-11-18 03:00 UTC by andrewkmin

2021-11-18 18:27 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +
Hey a few things here - 

1. This line `If you receieve an error that looks like this - `greadlink: command not found` you will need to do two things:` there are three steps here now if you could update :)

2. This `(locking your cargo version)[https://github.community/t/failed-sending-data-to-the-peer-connection-died-tried-5-times-before-giving-up/189130/4]` is actually not written correctly, it should be: 
[locking your cargo version](https://github.community/t/failed-sending-data-to-the-peer-connection-died-tried-5-times-before-giving-up/189130/4)

2021-11-18 18:31 UTC, adilanchian requested changes
Hey - 

Thanks for the changes here! Just a few thoughts here :)

2021-11-18 18:31 UTC, adilanchian commented on Solana_And_Web3/en/Section_3/Lesson_2_Call_Deployed_Program.md
> +	// If we hit this, it means the program account hasn't been initialized.
Can you remove these indents here please?

2021-11-28 21:37 UTC, adilanchian commented
Hey @andrewkmin !

Just throwing a quick tag here :). Let me know if you need help with any of these comments

2021-12-01 08:34 UTC, andrewkmin commented on Solana_And_Web3/en/Section_3/Lesson_2_Call_Deployed_Program.md
> +	// If we hit this, it means the program account hasn't been initialized.
done, let me know if this is what you intended to see :)

2021-12-01 08:38 UTC, andrewkmin commented on Solana_And_Web3/en/Section_4/Lesson_1_Finishing_Touches_Web_App_And_Program.md
> +Who needs Stripe and PayPal when you have a super low-gas fee blockchain that lets you make instant payments?!?
let me know what you think about this change; i'm assuming we want to highlight the low-gas nature of solana, but could be wrong here 😄

2021-12-02 22:23 UTC, adilanchian commented
Looks great! Thanks for working with me on this :)

2021-12-02 22:23 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

2021-12-02 22:23 UTC, merged

2021-12-02 22:24 UTC, adilanchian commented
@all-contributors please add @andrewkmin for doc