Remove redundant curly braces in jsx
buildspace/buildspace-projects pull request #430
Opened 2021-11-21 16:27 UTC by marcinsola

In the example for "Mint NFT" button, there were too many curly braces, which were causing the website to break. We only need the curly braces around the ternary operator. I removed the ones around the comment as well as the call to `renderNotConnectedContainer` function.

2021-11-21 16:42 UTC, adilanchian requested changes
Left a few thoughts here :)

Thanks!!

2021-11-21 16:42 UTC, adilanchian commented on NFT_Collection/en/Section_3/Lesson_3_Create_Button_To_Call_Contract.md
> +    /** Add askContractToMintNft Action for the onClick event **/
So we actually do need to make comments like `{/* Some comment goes here */}` as this comment lives in jsx land

Can you also do me a favor - on line 71 can you change ```javascript to ```jsx ?

Thank you!

2021-11-22 07:06 UTC, marcinsola commented on NFT_Collection/en/Section_3/Lesson_3_Create_Button_To_Call_Contract.md
> +    /** Add askContractToMintNft Action for the onClick event **/
Hmm, I'm getting an error when I put back the curly braces around the comment in replit, that's why I decided to remove them. We're opening the curly braces on line 73 already. That's actually why we don't need them around the `renderNotConnectedContainer` as well. Are you sure those are necessary?

2021-11-22 18:30 UTC, adilanchian commented on NFT_Collection/en/Section_3/Lesson_3_Create_Button_To_Call_Contract.md
> +    /** Add askContractToMintNft Action for the onClick event **/
Hey @marcinsola 

Thats solely for the comment haha. You're saying it works without the curlies for the comment?

2021-11-23 12:04 UTC, marcinsola commented on NFT_Collection/en/Section_3/Lesson_3_Create_Button_To_Call_Contract.md
> +    /** Add askContractToMintNft Action for the onClick event **/
Yup, we're already in a "js" context because of the curly brackets starting at line 73. Adding curlies for the method call as well as the comment causes repl to throw `Unexpected token` error.

2021-11-23 15:29 UTC, adilanchian commented on NFT_Collection/en/Section_3/Lesson_3_Create_Button_To_Call_Contract.md
> +    /** Add askContractToMintNft Action for the onClick event **/
@marcinsola Roger that! Thanks for the insight :)

2021-11-23 15:30 UTC, adilanchian commented
LGTM.

Thanks for working with me here :)

2021-11-23 15:30 UTC, merged

2021-11-23 15:30 UTC, adilanchian commented
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION 

🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩🤩

2021-11-23 15:30 UTC, adilanchian commented
@all-contributors please add @marcinsola for doc

2021-11-23 18:34 UTC, marcinsola commented
@adilanchian Thank you! Glad I could start helping! ;)