add fix for "toolchain '1.52.1-aarch64-apple-darwin' is not installed"
buildspace/buildspace-projects pull request #437
Opened 2021-11-22 23:47 UTC by torquan

I received this error when trying to run ```./scripts/cargo-install-all.sh .```.

Solution found here: https://github.com/rust-lang/rustup/issues/1793

2021-11-23 15:39 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +```
Can you do me a favor and change this to the following - 

```bash
rustup toolchain uninstall stable
rustup toolchain install stable
```

(just adding bash and then removing the indents)

2021-11-23 15:39 UTC, adilanchian requested changes
Good catch and thanks for adding :). 

Left some small comments for ya!

2021-11-23 19:51 UTC, torquan commented
done!

2021-11-28 21:42 UTC, adilanchian approved these changes
Very nice thank you!!

2021-11-28 21:42 UTC, merged

2021-11-28 21:42 UTC, adilanchian commented
ALSO CONGRATS ON YOUR FIRST PR 

😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊😊

2021-11-28 21:43 UTC, adilanchian commented
@all-contributors please add @torquan for doc