[NFT_Game] Change "you your" to "show your"
buildspace/buildspace-projects pull request #478
Opened 2021-11-30 02:27 UTC by quiint

"...OpenSea or Rarible should you your NFT w/..." doesn't make sense, so I changed it to "...OpenSea or Rarible should show your NFT w/..." 🙂

2021-12-02 22:30 UTC, adilanchian requested changes
Good catch :)

Thanks!!

2021-12-02 22:30 UTC, adilanchian commented on NFT_Game/en/Section_2/Lesson_2_Deploy_And_See_NFTs_Changing.md
> +Once you wait a few min, sites like OpenSea or Rarible should show your NFT w/ it's update HP #.
can you add an 's' at the end of min here?

2021-12-04 16:52 UTC, quiint commented on NFT_Game/en/Section_2/Lesson_2_Deploy_And_See_NFTs_Changing.md
> +Once you wait a few min, sites like OpenSea or Rarible should show your NFT w/ it's update HP #.
All fixed! 🙂

2021-12-04 17:17 UTC, adilanchian commented
Hey @quiint !

Thanks for this :). All good to go!

2021-12-04 17:17 UTC, merged

2021-12-04 17:17 UTC, adilanchian commented
@all-contributors please add @quiint  for doc

2021-12-04 17:18 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨

2021-12-04 17:19 UTC, quiint commented
> ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION
> 
> 
> 
> ✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨

Super excited 🎉