Resolve Issue #279
buildspace/buildspace-projects pull request #482
Opened 2021-11-30 19:34 UTC by stevedsimkins

Added "Check your Network" section starting line 102, making sure users have their network set to Rinkeby

2021-12-04 16:10 UTC, adilanchian requested changes
I love this - thanks for adding!

Just left a few comments for ya 🤘

2021-12-04 16:10 UTC, adilanchian commented on NFT_Game/en/Section_3/Lesson_4_Checking_For_Character_NFT.md
> +```
Can you add a bit of formatting here like so - 

```javascript
const checkNetwork = async () => {
  try { 
    if (window.ethereum.networkVersion !== '4') {
      alert("Please connect to Rinkeby!")
    }
  } catch(error) {
    console.log(error)
  }
}
```

2021-12-04 16:10 UTC, adilanchian commented on NFT_Game/en/Section_3/Lesson_4_Checking_For_Character_NFT.md
> +Now anytime the page is loaded on the mainnet you will get a notice for your users to switch to rinkeby!
I think right before this, a small explanation of what the 4 value means here would be ideal!

2021-12-07 15:21 UTC, stevedsimkins commented on NFT_Game/en/Section_3/Lesson_4_Checking_For_Character_NFT.md
> +```
Added formatting to latest commit!

2021-12-07 15:21 UTC, stevedsimkins commented on NFT_Game/en/Section_3/Lesson_4_Checking_For_Character_NFT.md
> +Now anytime the page is loaded on the mainnet you will get a notice for your users to switch to rinkeby!
Added explanation to latest comitt!

2021-12-07 16:07 UTC, stevedsimkins commented
Updated the patch with the changes requesed!

2021-12-07 17:03 UTC, adilanchian commented
@stevedsimkins this is DOPE. Thank you so much for this!!

2021-12-07 17:04 UTC, merged

2021-12-07 17:04 UTC, adilanchian commented
@all-contributors please add @stevedsimkins for doc

2021-12-07 17:04 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄🦄

2021-12-07 17:06 UTC, stevedsimkins commented
Thanks man!! Happy to help :)