Update m1_setup.md
buildspace/buildspace-projects pull request #486
Opened 2021-12-02 10:18 UTC by TylerWoolcott

Added instructions for troubleshooting Transaction simulation failed message to get deployment test to pass.

2021-12-04 16:27 UTC, adilanchian commented
Sup @TylerWoolcott !

Dang you're on a roll. Thank you so much for these! For this one, what is the _true_ issue? It sounds like maybe forgetting to add the program id in both `.toml` file and `.rs` file. Is this what you're seeing as well?

2021-12-05 10:30 UTC, TylerWoolcott commented
Hi @adilanchian, 

Yes exactly,  if I don't add the program id in both .toml file and .rs file it won't deploy and it's not mentioned in the docs to add the program id to the .rs file.

2021-12-06 21:52 UTC, adilanchian requested changes
Left some thoughts for you! Let me know what you think

2021-12-06 21:52 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This may take a while the first time you run it! As long as you get the green words the bottom that say "1 passing" you're good to go!! Keep us posted in the Discord if you run into issues here. Note
Based off what you said, I think this may sound a bit better here -

Note, if you get an error in your terminal that says: "Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist", this most likely means you forgot to add your Program Id in both your `.toml` file and .`rs` file! Go ahead and grab your ID again and verify it's updated in the appropriate spots :).

Also - can you make sure to add this block on a new line? Let me know your thoughts!

2021-12-07 14:12 UTC, TylerWoolcott commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This may take a while the first time you run it! As long as you get the green words the bottom that say "1 passing" you're good to go!! Keep us posted in the Discord if you run into issues here. Note
Hi @adilanchian, 

Thanks yes this makes sense. I incorporated the changes as you outlined and updated the PR below however it says the branch has an unrelated conflict before it can be merged (see below).

2021-12-07 17:09 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Resources/m1_setup.md
> +This may take a while the first time you run it! As long as you get the green words the bottom that say "1 passing" you're good to go!! Keep us posted in the Discord if you run into issues here. Note
Thanks for that! I can take care of this for ya :)

2021-12-07 17:10 UTC, merged

2021-12-07 17:10 UTC, adilanchian commented
Thank you so much for the change!!