Update lesson_3 Store_basic_data
buildspace/buildspace-projects pull request #487
Opened 2021-12-02 11:01 UTC by TylerWoolcott

Added instructions for fixing test error "Transaction simulation failed: Error processing Instruction 0: custom program error: 0x64".

2021-12-04 16:29 UTC, adilanchian commented
@TylerWoolcott the legend

One more question for you - why is this change necessary? If you have some resources that would be great! I would love to have a small explanation of why this is needed

2021-12-05 11:29 UTC, TylerWoolcott commented
Hi @adilanchian, 

It seems 9000 is not enough space for the account to run the program. By comparison, the Anchor docs defines a simple program that declares ``space = 8 + 8`` (eg, 8 kilobytes + 8 kilobytes): https://project-serum.github.io/anchor/tutorials/tutorial-1.html#defining-a-program

Similarly, Nader Dabit's program example uses ``space = 16 + 16``: https://dev.to/dabit3/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291

2021-12-06 21:57 UTC, adilanchian requested changes
Left some thoughts for you here!

2021-12-06 21:57 UTC, adilanchian commented on Solana_And_Web3/en/Section_2/Lesson_3_Store_Basic_Data.md
> +First we've got `[account(init, payer = user, space = 9000)]`. **All we're doing here is telling Solana how we want to initialize `BaseAccount`.** Note, if after running your test below you get the e
Based on what you said, I think it's a very valid point to add this, but I think we need to add a bit more explanation behind it. A few things for you - 

1. Can you make this new block on a new line please?
2. I think we should say something more along the lines of this - 
Note, if after running your test below you get the error `Transaction simulation failed: Error processing Instruction 0: custom program error: 0x64 `, you will need to change `space = 9000` to `space = 10000`. If you look at [these docs from anchor](https://project-serum.github.io/anchor/tutorials/tutorial-1.html#defining-a-program) you can see that they define a simple program that declares space = 8 + 8 (eg, 8 kilobytes + 8 kilobytes). The more logic we add to our program, the more space it will take up!

Let me know your thoughts :)

2021-12-07 14:43 UTC, TylerWoolcott commented on Solana_And_Web3/en/Section_2/Lesson_3_Store_Basic_Data.md
> +First we've got `[account(init, payer = user, space = 9000)]`. **All we're doing here is telling Solana how we want to initialize `BaseAccount`.** Note, if after running your test below you get the e
Hey @adilanchian, 

Thanks yes good suggestions, I added another commit with the changes below.

2021-12-07 17:37 UTC, adilanchian requested changes
Hey @TylerWoolcott - it looks like a lot of your changes are from your linter. Could you please revert those changes?

2021-12-09 13:16 UTC, TylerWoolcott commented
Hey @adilanchian, 

I reverted the linter changes and pushed again (hash # 3b1b3a8). It still says I made other changes but those 'other changes' are what the latest file looks like.

2021-12-09 22:52 UTC, adilanchian commented
@TylerWoolcott looking good! Thanks again :)

2021-12-09 22:52 UTC, merged