ertyurk-patch-cache-folder-warning-section-3-lesson-1
buildspace/buildspace-projects pull request #510
Opened 2021-12-04 14:54 UTC by ertyurk

Warning message added to whom may choose to not create assets folder under the project

2021-12-04 17:09 UTC, adilanchian requested changes
Lemme know your thoughts!

2021-12-04 17:09 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_1_Call_Candy_Machine_From_App.md
> +**Warning** `.cache/devent-temp` can be found on the top of `assets` folder after running Metaplex command in previous steps.
Thanks for this!! 

This is definitely the right approach here, but I think we can change up the wording here to look a little something like this:

**Note**: `.cache/devent-temp` can be found at the root of your folder after running the Metaplex command in previous steps.

2021-12-04 17:11 UTC, adilanchian commented
Looks like there is a merge conflict here as well!

2021-12-05 07:05 UTC, ertyurk commented on Solana_NFTs/en/Section_3/Lesson_1_Call_Candy_Machine_From_App.md
> +**Warning** `.cache/devent-temp` can be found on the top of `assets` folder after running Metaplex command in previous steps.
Hey @adilanchian , Let me add that, thank you 👍🏼

2021-12-05 07:06 UTC, ertyurk commented
@adilanchian I resolved the conflict, sorry for the extra spacing :)

2021-12-09 22:55 UTC, adilanchian commented
Hey @ertyurk thanks so much for this! Look good to me :)

2021-12-09 22:55 UTC, merged

2021-12-09 22:56 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION 

😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎

2021-12-09 22:56 UTC, adilanchian commented
@all-contributors please add @ertyurk  for doc