Improve NFT images loading time
buildspace/buildspace-projects pull request #528
Opened 2021-12-04 20:09 UTC by zeosamaster

`fetchHashTable` resorts to `MetadataProgram.getProgramAccounts` to get all accounts and that takes a lot of time to respond.

To improve the loading time a bit, we can request the NFT metadata in parallel (as opposed to sequentially).
Instead of waiting for the first NFT's metadata to be loaded before requesting the second NFT's metadata (this creates a bottleneck, considering we'll have 3 sequential requests), we request all the metadata at once and then wait until we get it all back to store all the images in the state in one go.

2021-12-06 22:09 UTC, adilanchian requested changes
I like this change a lot! Makes a lot of sense :)

I left a few comments to see your thoughts!

2021-12-06 22:09 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
>  }
I think this entire function should now be wrapped in a `try / catch` thoughts?

2021-12-06 22:09 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_3_Build_Loading_States.md
> +}
Add the `try/catch`

2021-12-08 02:27 UTC, zeosamaster commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
>  }
Given that there was no error handling previously, I didn't want to include too much of a change in one go (to avoid confusing what the actual introduced change was).
But totally agree with that, gonna cook that up when I get the time, thanks for the suggestion 👍

2021-12-09 23:01 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
>  }
ya thats all good! Would be amazing :) thank you!

2021-12-10 21:56 UTC, zeosamaster commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
>  }
Done, sorry for taking so long!
If any request fails, it'll simply disregard that mint and proceed to the remaining. Any failed request will be filtered out.
Let me know if it looks good :)

2021-12-12 16:25 UTC, adilanchian requested changes
Left some thoughts here! I think there are a few bugs in this actually

2021-12-12 16:25 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +      return null;
So here I would say we probably want to log out the error right? So we know what failed and why!

Also - does this map not throw an error right now? In your callback method, you are using the await keyword, but you don't define it as async

2021-12-12 16:25 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +  const filteredMints = allMints.filter(mint => mint !== null);
I also don't believe this will work based on this:

> It rejects immediately upon any of the input promises rejecting or non-promises throwing an error, and will reject with this first rejection message / error.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

2021-12-12 16:30 UTC, zeosamaster commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +  const filteredMints = allMints.filter(mint => mint !== null);
That actually works. The error is caught on the try/catch, it's not spilling to the Promise.all.
Any failed requests will be caught, handled and resolve successfully.

2021-12-12 16:30 UTC, zeosamaster commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +      return null;
Right, well caught 🤦 
Adding the async and logging the error 👌

2021-12-12 16:31 UTC, zeosamaster commented
Changes pushed, thanks for catching the async error 🙏

2021-12-18 14:54 UTC, adilanchian requested changes
Sorry for the late reply here!!

Looks good other than that one section I pointed out :)

2021-12-18 14:54 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_3_Build_Loading_States.md
> +}
This needs to be updated properly right?

2021-12-18 16:53 UTC, zeosamaster commented on Solana_NFTs/en/Section_3/Lesson_3_Build_Loading_States.md
> +}
You meant the second occurrence in `Lesson_2_Create_Mint_NFT_Button.md`, right? Forgot there were two occurrences in that file, sorry about that. Updated it now.

Sorry for the mess, I think I got it right now 😅

2021-12-22 16:06 UTC, adilanchian requested changes
Sorry for the late reply here - it's been quite busy!!

So I just found a bug actually - lemme know what you think

2021-12-22 16:06 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> -      setMints((prevState) => [...prevState, parse.image]);
Hey don't we still need this? 

Everytime you reload the page this will actually duplicate all the NFTs that were minted!

2021-12-22 16:34 UTC, zeosamaster commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> -      setMints((prevState) => [...prevState, parse.image]);
That isn't needed here, since with the new approach the whole state is getting set with `setMints(filteredMints)`. You don't need to look at the previous state to add an image (neither check if it's already there). All the images are unique and you can set the whole collection at once.

To illustrate this, imagine you have NFT1, NFT2 and NFT3.
With the previous approach, you're fetching the hashtable, getting the 3 NFTs and then requesting NFT1's metadata, checking if the state already has that image and storing it along all other currently stored images, then moving on to NFT2 and NFT3.
With the new approach, you're fetching the same hashtable and then fetching the metadata for all 3 NFTs at once. When you get them all back (after `Promise.all`), you have a list of 3 images for the 3 minted NFTs and that list completely replaces your previous state, no matter what images you previously had stored. You'll end up with 3 images on the UI.
The only way you get duplicated images on the UI is if you have multiple NFTs with the same image. If you think that's a problem, I can filter out duplicates before setting the state, no problem. In my opinion that'll be confusing because you'll have less images on the UI than minted NFTs. Let me know what you think.

As for reloading the page, I didn't understand what you meant. Reloading the page triggers the requests again and you'll have a clean state and set the whole image list nonetheless, there's no duplication.

2021-12-27 22:14 UTC, adilanchian commented
Hey @zeosamaster -

Thanks so much for working with me here and sorry for the late reply haha. Ya great explanation! I completely missed out you were setting the state :).

I say lets go ahead and give it ago! Thanks again for the time

2021-12-27 22:14 UTC, merged

2021-12-27 22:14 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

✨✨

2021-12-27 22:15 UTC, adilanchian commented
@all-contributors please add @zeosamaster  for doc