`Exiled Ape`
buildspace/buildspace-projects pull request #534
Opened 2021-12-05 03:04 UTC by jcstein

2021-12-06 22:20 UTC, adilanchian requested changes
Small change I left for ya :)

2021-12-06 22:20 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +In your `CandyMachine` component you'll see a function named `mintToken`. This is part of Metaplex's front-end library *(huge **shoutout to the [Exiled Apes Candy Machine Mint repo](https://github.co
Can you add `huge` in the bolded content please :)?

2021-12-06 22:34 UTC, jcstein commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +In your `CandyMachine` component you'll see a function named `mintToken`. This is part of Metaplex's front-end library *(huge **shoutout to the [Exiled Apes Candy Machine Mint repo](https://github.co
absolutely! my apologies for the half-pull request 😅

2021-12-06 22:40 UTC, jcstein reviewed
✅

2021-12-07 17:41 UTC, adilanchian commented
POG. Thank you for this :)

2021-12-07 17:41 UTC, merged