npm install -g errors
buildspace/buildspace-projects pull request #538
Opened 2021-12-05 13:05 UTC by matanwrites

Add link to fix npm install -g EACCESS permissions errors

2021-12-06 22:27 UTC, adilanchian requested changes
Hey @matanwrites !

Thanks for the contribution! Left a small comment for ya :). Thanks!

2021-12-06 22:27 UTC, adilanchian commented on Solana_NFTs/en/Section_2/Lesson_1_Get_Solana_Running.md
> +> If you run into EACCES permissions errors while installing, please checkout this [link](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-
What are your thoughts on changing this link to be: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally instead?

2021-12-12 21:06 UTC, matanwrites commented on Solana_NFTs/en/Section_2/Lesson_1_Get_Solana_Running.md
> +> If you run into EACCES permissions errors while installing, please checkout this [link](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-
Sure, agree let's let users choose however they want to fix it!

2021-12-12 21:15 UTC, matanwrites commented
Done! :)

2021-12-18 14:58 UTC, adilanchian approved these changes
Beautiful. Thank you for this!

2021-12-18 14:58 UTC, merged