Simple grammar fixes
buildspace/buildspace-projects pull request #541
Opened 2021-12-05 16:53 UTC by tyirenkyi

2021-12-05 20:01 UTC, aftr101 approved these changes

2021-12-06 22:29 UTC, adilanchian requested changes
Nice catches here :)

Left a very small comment for ya if you don't mind!

2021-12-06 22:29 UTC, adilanchian commented on Solana_NFTs/en/Section_0/Lesson_2_Whats_Different_About_Solana_NFTs.md
> +Candy machine also has some other goodies it gives us as well which we'll cover later but I hope this overview helps later down the line!! Feel free to come back to it once you get more into the cand
can you add a comma after later here please?

2021-12-09 00:54 UTC, tyirenkyi commented on Solana_NFTs/en/Section_0/Lesson_2_Whats_Different_About_Solana_NFTs.md
> +Candy machine also has some other goodies it gives us as well which we'll cover later but I hope this overview helps later down the line!! Feel free to come back to it once you get more into the cand
Sure, on it

2021-12-09 01:00 UTC, tyirenkyi commented on Solana_NFTs/en/Section_0/Lesson_2_Whats_Different_About_Solana_NFTs.md
> +Candy machine also has some other goodies it gives us as well which we'll cover later but I hope this overview helps later down the line!! Feel free to come back to it once you get more into the cand
done

2021-12-09 23:05 UTC, adilanchian commented
Cheers! Thanks for this :)

2021-12-09 23:05 UTC, merged

2021-12-09 23:06 UTC, adilanchian commented
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨

2021-12-09 23:06 UTC, adilanchian commented
@all-contributors please add @tyirenkyi for doc