Resolve Issue #82
buildspace/buildspace-projects pull request #560
Opened 2021-12-07 20:02 UTC by stevedsimkins

Added some suggestions for diving deeper into NFT smart contracts per Issue #82

2021-12-09 23:14 UTC, adilanchian commented
Sup @stevedsimkins !

Thanks for adding this :). Looks pretty sick! Going to add @farzaa to see if he has some thoughts here as well!

2021-12-18 15:12 UTC, adilanchian commented
Hi @stevedsimkins !!

Thanks for another cool PR:). Sorry I have been really busy and haven't been able to look too much into this :(. Will get back to it asap!

2021-12-18 15:16 UTC, stevedsimkins commented
No worries!! I know y'all are busy; just doing my part :)

2021-12-22 16:12 UTC, adilanchian requested changes
Looking good :). 

Can you just make these minor changes for me?

2021-12-22 16:12 UTC, adilanchian commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +- Sell your NFTs - Right now your users only have to pay gas fees to mint your awesome nfts and you're not getting any of that money! There are several ways to alter your smart contract that make the
Can you bold **Sell your NFTs**?

2021-12-22 16:12 UTC, adilanchian commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +- Add Royalties! - You can also add royalties to your smart contract that would give you a percentage of every future sale of your NFT! Read more about it here: [EIP-2981: NFT Royaly Standard](https:
Can you bold **Add Royalties** and remove the `!`?

2021-12-22 16:12 UTC, adilanchian commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +- Test your contracts locally - If you want to test your contracts more extensively without deploying to a test net like Rinkeby, Hardhat of course will let you do that! Best way to achieve that is t
Can you bold **Test your contracts locally**?

2021-12-26 00:47 UTC, stevedsimkins commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +- Sell your NFTs - Right now your users only have to pay gas fees to mint your awesome nfts and you're not getting any of that money! There are several ways to alter your smart contract that make the
Done!

2021-12-26 00:47 UTC, stevedsimkins commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +- Add Royalties! - You can also add royalties to your smart contract that would give you a percentage of every future sale of your NFT! Read more about it here: [EIP-2981: NFT Royaly Standard](https:
Done!

2021-12-26 00:47 UTC, stevedsimkins commented on NFT_Collection/en/Section_4/Lesson_2_Ship_It.md
> +- Test your contracts locally - If you want to test your contracts more extensively without deploying to a test net like Rinkeby, Hardhat of course will let you do that! Best way to achieve that is t
Done!

2021-12-26 00:47 UTC, stevedsimkins commented
Completed all minor requested changes!

2021-12-27 22:16 UTC, adilanchian approved these changes
Looks great!! TY :)

2021-12-27 22:17 UTC, merged