Added slight clarification to "Error to be aware of"
buildspace/buildspace-projects pull request #564
Opened 2021-12-08 02:27 UTC by stevedsimkins

Saw a lot of users on the discord struggling with this, tried to make it flash in people's faces a bit more and clarify the problem they're facing!

2021-12-12 16:50 UTC, adilanchian requested changes
Appreciate the call out! 

Just one change please :)

2021-12-12 16:50 UTC, adilanchian commented on Solana_NFTs/en/Section_2/Lesson_3_Depoy_NFTs_To_Devnet.md
> +## 😡 **Error to be aware of.**
Can we keep this as h3?

2021-12-14 02:38 UTC, stevedsimkins commented on Solana_NFTs/en/Section_2/Lesson_3_Depoy_NFTs_To_Devnet.md
> +## 😡 **Error to be aware of.**
done!

2021-12-14 02:38 UTC, stevedsimkins commented
Made the changes; ready to merge!

2021-12-18 15:22 UTC, adilanchian commented
Thanks for this @stevedsimkins !

2021-12-18 15:22 UTC, merged