Specify which toml file is being warned about
buildspace/buildspace-projects pull request #583
Opened 2021-12-11 06:45 UTC by zisko

There is a Cargo.toml file that can be confused in this warning.

2021-12-22 18:28 UTC, adilanchian requested changes
Core changes look good - 

Just remove your changes you made to the `README` && `.all-contributors` file :).

2021-12-22 18:28 UTC, adilanchian commented on .all-contributorsrc
> +      ]
You don't need to add this :). We have a bot that does all this automatically!

2021-12-22 18:28 UTC, adilanchian commented on README.md
> +    <td align="center"><a href="https://github.com/tyirenkyi"><img src="https://avatars.githubusercontent.com/u/39198645?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Timothy Yirenkyi</b></sub></a>
Same here

2021-12-27 22:28 UTC, adilanchian commented
@zisko - friendly ping here to see if you are still wanting to do this :)

2021-12-29 22:57 UTC, zisko commented on .all-contributorsrc
> +      ]
so weird! I must have pulled in those changes accidentally- fixing now.

2021-12-29 22:57 UTC, zisko commented
Fixed :)

2022-01-04 19:50 UTC, adilanchian approved these changes
Sorry for the late reply - 

Looks great! TY!

2022-01-04 19:50 UTC, merged

2022-01-04 19:51 UTC, adilanchian commented
@all-contributors please add @zisko  for doc