Fixed some typos in the lesson
buildspace/buildspace-projects pull request #616
Opened 2021-12-19 16:58 UTC by helloitsm3

Fixed typo in section 3 lesson 1 of Solana Metaplex lesson
   - Changed "add the follow code" to "add the following code"

Fixed typo in Solana Metaplex lesson
  - Reduced Solana airdrop amount from 5 to 2.

2021-12-23 21:53 UTC, adilanchian commented
Hey @helloitsm3 !

Before we continue here, can you do one more fetch from the remote to make sure you are up to date :)?

2021-12-24 09:53 UTC, helloitsm3 commented
> re

Yup, done that :)

2021-12-26 13:40 UTC, adilanchian requested changes
Looking good! Just left a few comments for you :)

2021-12-26 13:40 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +  Token.createMintToInstruction(TOKEN_PROGRAM_ID, mint.publicKey, token, walletAddress.publicKey, [], 1),
Can you revert this please?

2021-12-26 13:40 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +  { commitment: "processed" }
You can revert this as well :). We like single quotes hehe

2021-12-27 04:19 UTC, helloitsm3 commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +  { commitment: "processed" }
Done :)

2021-12-27 20:29 UTC, adilanchian requested changes
Left some thoughts :) ty!

2021-12-27 20:29 UTC, adilanchian commented on .gitignore
> +.vscode
We actually can remove this!  :)

2021-12-27 20:29 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
>        </button>
Can we keep this double quotes please?

2022-01-04 20:36 UTC, adilanchian requested changes
Left another small comment for you !

Also - can you please not commit your `.vscode` file? 

Thanks!

2022-01-04 20:36 UTC, adilanchian commented on Solana_NFTs/en/Section_3/Lesson_2_Create_Mint_NFT_Button.md
> +   Token.createInitMintInstruction(
This space should be removed!

2022-01-19 03:40 UTC, NickGonzalez04 commented
@adilanchian This looks good to go! Will come back around and make sure this is still good since the Candy machine went to V2 and there were some dock changes.

2022-01-20 20:29 UTC, adilanchian commented
Hey @NickGonzalez04 sounds good!! ty :)

2022-02-16 14:27 UTC, adilanchian commented
Closing do to inactivity !

2022-02-16 14:27 UTC, closed without merging