Bugfix - mintNFT
buildspace/buildspace-projects pull request #620
Opened 2021-12-19 23:56 UTC by smckisson

mintNFT can unintentionally set hasClaimedNFT to true. If function errors, finally block will be called and still set state var to true even if minting fails. Change wraps block in .then instead of .finally

2021-12-20 07:33 UTC, helloitsm3 approved these changes

2021-12-20 11:01 UTC, nachoiacovino approved these changes
lgtm

2021-12-24 00:23 UTC, adilanchian requested changes
Nice change!

Can you just make sure this is indented properly :)?

2021-12-24 00:23 UTC, adilanchian commented on JS_DAO/en/Section_2/Lesson_3_Let_Users_Mint_Your_NFT.md
> +    };
Looks like you have an extra indent here! Can you make sure this is indented properly?

2021-12-26 15:34 UTC, adilanchian requested changes
Indentation still seems a bit off?

2021-12-26 15:34 UTC, adilanchian commented on JS_DAO/en/Section_2/Lesson_3_Let_Users_Mint_Your_NFT.md
> +    };
This indentation still looks off no?

2021-12-27 17:34 UTC, smckisson commented on JS_DAO/en/Section_2/Lesson_3_Let_Users_Mint_Your_NFT.md
> +    };
Looks like my formatter is using 2 tabs by default and single quotes. Tried to make it match original formatting now

2021-12-27 20:30 UTC, adilanchian commented
Hey @smckisson -

Thanks for the changes! LGTM!

2021-12-27 20:31 UTC, merged