Updated lesson 3 - script 9 with dotenv
buildspace/buildspace-projects pull request #637
Opened 2021-12-21 16:27 UTC by jtordgeman

the script is using `process.env.WALLET_ADDRESS` but didnt have dotenv imported.

2021-12-21 20:05 UTC, nachoiacovino requested changes
things that you changed were incorrect.

token -> tokens is correct though.

If you modify the PR to only include that we'll get it merged.

2021-12-21 20:05 UTC, nachoiacovino commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +import dotenv from "dotenv";
we don't need this here

2021-12-21 20:05 UTC, nachoiacovino commented on JS_DAO/en/Section_3/Lesson_3_Building_Treasury_And_Governance.md
> +import dotenv from "dotenv";
we don't need this here

2021-12-21 20:05 UTC, nachoiacovino commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +    console.error("failed to create second proposal", error);
this is incorrect, it's the second

2021-12-21 20:14 UTC, jtordgeman commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +import dotenv from "dotenv";
if you dont use dotenv here how will node read the env variable? unless you have it saved somewhere already or run WALLET_ADDRESS=<whatever> node scripts/...

2021-12-21 20:18 UTC, jtordgeman commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +    console.error("failed to create second proposal", error);
its the second - on the original error it says first (which is already handled for the first proposal)

2021-12-21 21:57 UTC, nachoiacovino commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +import dotenv from "dotenv";
because we're importing script 1 and we have it there.

2021-12-21 22:00 UTC, nachoiacovino commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +    console.error("failed to create second proposal", error);
you're right!

Delete the dotenv stuff and we can merge this, sorry I got confused.

2021-12-21 22:23 UTC, jtordgeman commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +    console.error("failed to create second proposal", error);
done :)

2021-12-21 23:13 UTC, nachoiacovino approved these changes
lgtm!

2021-12-24 00:53 UTC, merged

2021-12-24 00:53 UTC, adilanchian commented
Hey @jtordgeman -

Looking good! Thanks for this :)

2021-12-24 00:53 UTC, adilanchian commented
ALSO CONGRATS ON YOUR FIRST CONTRIBUTION

👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

2021-12-24 00:54 UTC, adilanchian commented
@all-contributors please add @jtordgeman for doc