Add instructions to keep private key secure
buildspace/buildspace-projects pull request #643
Opened 2021-12-22 00:32 UTC by yoyothesheep

Add explicit instructions for .gitignore, so users don't commit their private key by accident.

2021-12-26 15:43 UTC, adilanchian requested changes
this is probably a smart move !

One thing I would say as well is when we talk about this `.env` file, can you add a call out to this?

2021-12-26 15:43 UTC, adilanchian commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +In the meantime - open your `.gitignore` file and add a line for hardhat.config.js. You can remove this later when you set up `.env`.
Can you add backticks around hardhat.config.js please?

2021-12-26 21:27 UTC, yoyothesheep commented on NFT_Collection/en/Section_1/Lesson_4_Create_A_Contract_That_Mints_NFTs.md
> +In the meantime - open your `.gitignore` file and add a line for hardhat.config.js. You can remove this later when you set up `.env`.
Done

2021-12-26 21:35 UTC, yoyothesheep commented
OK updated per your comments, pls take another look

2021-12-27 20:32 UTC, adilanchian commented
Hey @yoyothesheep -

Looks great! Thanks so much for the changes! 

LGTM

2021-12-27 20:32 UTC, merged

2021-12-27 20:33 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2021-12-27 20:38 UTC, adilanchian commented
@all-contributors please add @yoyothesheep  for doc