Update fix MintButton bug - Lesson_3_Let_Users_Mint_Your_NFT.md
buildspace/buildspace-projects pull request #644
Opened 2021-12-22 00:38 UTC by k8ives

This proposed change to the content is to reflect updated code under "Build a Mint NFT button section. The updated code fixes a bug that was allowing users to pass to the DAO member page even if they did not complete the NFT minting process. This change is based on a PR request by another user  [#620 ] - but that PR request had an errant ";" before ".catch((err) that caused a syntax error in replit and it wouldn't compile. this change removes the problem ";". Nacho said he would take care of the PR for the actual code in buildspace-dao-final.

2021-12-22 17:08 UTC, smckisson commented
> This proposed change to the content is to reflect updated code under "Build a Mint NFT button section. The updated code fixes a bug that was allowing users to pass to the DAO member page even if they did not complete the NFT minting process. This change is based on a PR request by another user [#620 ] - but that PR request had an errant ";" before .catch((err) that caused a syntax error in replit and it wouldn't compile. this change removes the problem ";". Nacho said he would take care of the PR for the actual code in buildspace-dao-final.

Good catch on the code PR. Thank you! I fixed the compilation error and pulled the logic out into a function to match what was in the project content. Project content had mintNft logic in a function and final project code had it inline. Made them consistent now

2021-12-26 15:46 UTC, adilanchian requested changes
Hey @k8ives -

thanks so much for the contribution! Curious - why did you decide to completely rm the `mintNft` function? I feel like we should still keep that in there for now :).

2021-12-26 16:48 UTC, k8ives commented
@adilanchian im still a coding newb - i initially saw the solution on discord which had the code inline. i'll admit i was confused by it at the time, but thought maybe there was a reason for it that I didn't understand. in hindsight, i agree it would make more sense to keep the mintNFT function

2021-12-27 20:40 UTC, adilanchian commented
Hey @k8ives -

Yo no worries at all! It's awesome you're contributing so thank you!

Ya if you can go ahead and just add your changes to that `mintNFT` function that would be SAWEET.

2021-12-27 22:32 UTC, adilanchian requested changes
Almost there!!

Indentation looks a tad off still :)

2021-12-27 22:32 UTC, adilanchian commented on JS_DAO/en/Section_2/Lesson_3_Let_Users_Mint_Your_NFT.md
> +}
The indention here is just a TAD off :)

Can you correct this for me please?

2022-01-04 20:40 UTC, adilanchian commented
Hey @k8ives -

Sorry for the late reply! Everything looks great and will go ahead and merge this in :)

2022-01-04 20:40 UTC, merged

2022-01-04 20:40 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR FIRST CONTRIBUTION

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

2022-01-04 20:40 UTC, adilanchian commented
@all-contributors please add @k8ives  for doc