Fixed console.log logic Sec3 Lesson 4 (JSDAO)
buildspace/buildspace-projects pull request #663
Opened 2021-12-22 19:30 UTC by TrinidadHype

Currently in Section 3 Lesson 4 where we are setting up our voteModule, there is a console.log that prints whether a user has voted or not. The intended behaviour is to have it only print if the user already voted.

I have changed the logic to only print when the user has actually voted.

2021-12-25 13:33 UTC, nachoiacovino approved these changes

2021-12-26 16:07 UTC, adilanchian requested changes
Really good catch!

Can you make one small change for me please :)?

2021-12-26 16:07 UTC, adilanchian commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +      if(hasVoted) {
Can you add a space between `if` and `(hasVoted)` ?

2021-12-26 16:40 UTC, TrinidadHype commented on JS_DAO/en/Section_3/Lesson_4_Let_Users_Vote_On_Proposals.md
> +      if(hasVoted) {
Submitted the change, it should now have the space between `if` and `(hasVoted)` :)

2021-12-27 20:49 UTC, adilanchian commented
Cheers @TrinidadHype !

2021-12-27 20:49 UTC, merged

2021-12-27 20:49 UTC, adilanchian commented
ALSO - CONGRATS ON YOUR VERY FIRST GITHUB CONTRIBUTION!!

👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

2021-12-27 20:49 UTC, adilanchian commented
@all-contributors please add @TrinidadHype  for doc