Update Lesson_3_Let_Users_Mint_Your_NFT.md
buildspace/buildspace-projects pull request #691
Opened 2021-12-24 05:22 UTC by ngnathan

Fix typo "on" to "one" (end of sentence):

`Nice! Here you'll see my NFT here has "6 owners". You’ll also see it says “You own 1” which you’d see on your end as well as long as you minted one!`

2021-12-27 21:31 UTC, adilanchian requested changes
Just added one small change here :)

Thanks for the catch here!!

2021-12-27 21:31 UTC, adilanchian commented on JS_DAO/en/Section_2/Lesson_3_Let_Users_Mint_Your_NFT.md
> +Nice! Here you'll see my NFT here has "6 owners". You’ll also see it says “You own 1” which you’d see on your end as well as long as you minted one!
Can you tweak this to say:

Nice! Here you'll see my NFT has "6 owners". You’ll also see it says “You own 1” which you’d see on your end as well as long as you minted one!

2022-01-04 19:28 UTC, ngnathan commented
@adilanchian Thanks for reviewing!  Changes have been commited.

2022-01-04 21:01 UTC, adilanchian commented
Hey @ngnathan -

Sorry for the late reply here! Looks great :). TY!

2022-01-04 21:01 UTC, adilanchian approved these changes

2022-01-04 21:01 UTC, merged

2022-01-04 21:01 UTC, adilanchian commented
@all-contributors please add @ngnathan  for doc