Rephrase "Create these two events..." so it is clearer
buildspace/buildspace-projects pull request #739
Opened 2021-12-31 13:30 UTC by kuriakinzeng

2022-01-04 21:45 UTC, adilanchian requested changes
Made some changes! Let me know your thoughts :)

2022-01-04 21:45 UTC, adilanchian commented on NFT_Game/en/Section_2/Lesson_3_Adding_Utility_Functions.md
> +We create `CharacterNFTMinted` event under `mapping(address => uint256) public nftHolders`. We need to basically tell Solidity the format of our events before we start firing them. I also added an `A
Can you change this to say -

We create the `CharacterNFTMinted` event under `mapping(address => uint256) public nftHolders`. Why? Well, we need to tell Solidity the format of our events before we start firing them. You can see I also added an `AttackComplete` event which will be useful when we build our UI for "attacking" the boss — since we'll need to know if the attack was successful!

2022-01-12 14:11 UTC, kuriakinzeng commented on NFT_Game/en/Section_2/Lesson_3_Adding_Utility_Functions.md
> +We create `CharacterNFTMinted` event under `mapping(address => uint256) public nftHolders`. We need to basically tell Solidity the format of our events before we start firing them. I also added an `A
Thanks for the suggestion! I have committed the changes.

2022-01-19 04:00 UTC, NickGonzalez04 commented
@adilanchian Looks good to go!

2022-01-19 18:48 UTC, merged

2022-01-19 18:50 UTC, adilanchian commented
@all-contributors please add @kuriakinzeng for doc