changes made in S2L2 Transactions
buildspace/buildspace-projects pull request #751
Opened 2022-01-04 16:40 UTC by ropats16

Hi devs! I am issuing a request to change the following line in the Section 2 Lesson 2 (Setting up to deploy a blockchain) of Intro to Web3 under the Transactions sub-heading:
"For example, sending someone Ethereum is a transaction".

It must be changed to:
"For example, sending Ether (ETH) is a transaction".

This is to prevent new comers from being confused between Ethereum and Ether.

Thanks!!

2022-01-04 22:25 UTC, adilanchian requested changes
Hey @ropats16 !

Very nice catch :). Left one small comment for ya !

TY

2022-01-04 22:25 UTC, adilanchian commented on Solidity_And_Smart_Contracts/en/Section_2/Lesson_2_Deploy_To_Real_Testnet.md
> +So, when we want to perform an action on the Ethereum blockchain we call it a *transaction*. For example, sending someone Ether (ETH) is a transaction. Doing something that updates a variable in our
We can actually just fully change this to ETH in my opinion!

2022-01-05 03:42 UTC, ropats16 commented on Solidity_And_Smart_Contracts/en/Section_2/Lesson_2_Deploy_To_Real_Testnet.md
> +So, when we want to perform an action on the Ethereum blockchain we call it a *transaction*. For example, sending someone Ether (ETH) is a transaction. Doing something that updates a variable in our
Yeah. Thanks for the quick response! I mentioned both Ether and ETH so that you could choose whatever is in line with buildspace's teaching goals. Really love the work y'all are doing!

2022-01-06 18:19 UTC, adilanchian commented on Solidity_And_Smart_Contracts/en/Section_2/Lesson_2_Deploy_To_Real_Testnet.md
> +So, when we want to perform an action on the Ethereum blockchain we call it a *transaction*. For example, sending someone Ether (ETH) is a transaction. Doing something that updates a variable in our
Much appreciated!!

Ya feel free to just change this to ETH for me :). TY!

2022-01-07 12:26 UTC, ropats16 commented on Solidity_And_Smart_Contracts/en/Section_2/Lesson_2_Deploy_To_Real_Testnet.md
> +So, when we want to perform an action on the Ethereum blockchain we call it a *transaction*. For example, sending someone Ether (ETH) is a transaction. Doing something that updates a variable in our
Hey, I've changed it to ETH directly in my gitHub project. Since this was my first pull request I'm not sure what im supoosed to do. Should I change it in my local repo on PC and push it to github instead?

2022-01-12 00:26 UTC, adilanchian commented on Solidity_And_Smart_Contracts/en/Section_2/Lesson_2_Deploy_To_Real_Testnet.md
> +So, when we want to perform an action on the Ethereum blockchain we call it a *transaction*. For example, sending someone Ether (ETH) is a transaction. Doing something that updates a variable in our
^ thats it! You will have to Fork our repo and go from there :). Take a look at our README! Tells you exactly how to get started :). You got this!

2022-01-12 10:47 UTC, ropats16 commented on Solidity_And_Smart_Contracts/en/Section_2/Lesson_2_Deploy_To_Real_Testnet.md
> +So, when we want to perform an action on the Ethereum blockchain we call it a *transaction*. For example, sending someone Ether (ETH) is a transaction. Doing something that updates a variable in our
Hey Alec, it's done. Thanks for the support! Buildspace has helped me grow even by helping our community grow. :)

2022-01-19 04:08 UTC, NickGonzalez04 commented
@adilanchian We can close this PR @ropats16 made their first pr #793 ! (Will review and drop a comment in that one)

2022-01-19 18:51 UTC, adilanchian commented
@NickGonzalez04 cheers m8!!

2022-01-19 18:51 UTC, closed without merging