simplify idl workflow by using anchor idl init and Program.fetchIdl
buildspace/buildspace-projects pull request #769
Opened 2022-01-06 20:47 UTC by matanwrites

This help simplify workflow by using anchor to upload the idl to the blockchain instead of copying pasting the idl file around, hopefully this will reduce errors for students.

2022-01-19 18:55 UTC, adilanchian commented
Hey @matanwrites !

This is SO SICK. @NickGonzalez04 @AlmostEfficient  - would you be down to test this out and see if it's good to go?

TY!

2022-01-28 18:59 UTC, NickGonzalez04 commented
> Hey @matanwrites !
> 
> This is SO SICK. @NickGonzalez04 @AlmostEfficient - would you be down to test this out and see if it's good to go?
> 
> TY!

Will test this out today, so we can merge this over!

2022-02-16 14:29 UTC, adilanchian commented
Yooo @NickGonzalez04 - curious if you ever got to this?

2022-08-28 04:49 UTC, helloitsm3 commented
Here's the updated link to the documentation https://www.anchor-lang.com/docs/cli#idl

2022-08-29 09:55 UTC, helloitsm3 requested changes
You need to update the code in `Solana_And_Web3/en/Section_3/Lesson_3_Submitting_GIF_To_Solana.md` to fix the provider error. You removed `const provider = getProvider()` which will cause an error since you are using it in your `addGif` function

2022-08-29 18:44 UTC, mwrites commented
@helloitsm3 done! Last time I touched this PR was in January so I am not sure if the rest of the files still make sense with my changes, cheers!

2022-08-30 02:37 UTC, helloitsm3 commented
> @helloitsm3 done! Last time I touched this PR was in January so I am not sure if the rest of the files still make sense with my changes, cheers!

Yup, don't worry about it. Thanks for taking the time to edit this. I'll take a look at it

2022-08-30 04:50 UTC, helloitsm3 commented
@mwrites you're also missing a `const provider = await getProvider()` in here https://github.com/mwrites/buildspace-projects/blob/f2573f7808104977dff1f827c19190de3ec7f7d8/Solana_And_Web3/en/Section_3/Lesson_2_Call_Deployed_Program.md?plain=1#L284

2022-08-30 04:52 UTC, helloitsm3 commented
@adilanchian Once the necessary changes are made, you can merge this. Just tested it and seems like it's working.

2022-09-19 02:14 UTC, AlmostEfficient approved these changes

2022-09-19 02:14 UTC, merged