Add best practice tip for wallet management
buildspace/buildspace-projects pull request #772
Opened 2022-01-07 09:02 UTC by developing-coder

Suggest keeping investing and development wallets separate

2022-01-20 20:32 UTC, adilanchian requested changes
Looks great! Just have a small ask here :)

TY!

2022-01-20 20:32 UTC, adilanchian commented on NFT_Game/en/Section_1/Lesson_5_Deploy_To_Rinkeby.md
> +**BEST PRACTICE! Create a new account in MetaMask strictly for development purposes. This way, if your development account credentials accidentally leak, your real funds will still be safe.**
Can you change "BEST PRACTICE" to be - "Note:"

2022-01-21 07:14 UTC, developing-coder commented on NFT_Game/en/Section_1/Lesson_5_Deploy_To_Rinkeby.md
> +**BEST PRACTICE! Create a new account in MetaMask strictly for development purposes. This way, if your development account credentials accidentally leak, your real funds will still be safe.**
Done!

2022-01-21 19:53 UTC, adilanchian commented
Sweet thank you!

2022-01-21 19:53 UTC, merged