More updates to section 2
buildspace/buildspace-projects pull request #776
Opened 2022-01-07 20:20 UTC by rodsemi

Again credit to Okumu on discord for figuring this out! Adding an update to the how 0.json, 1.json, and 2.json should look like and also adding a config.json so CMv2 can work similar to CMv1 (for more info on config.json https://docs.metaplex.com/candy-machine-v2/configuration)

2022-01-21 00:02 UTC, adilanchian commented
Hey @rodsemi !

Thanks again for more work here!! Same as your other PR, going to hold off on these for a bit to verify with Raza

2022-01-31 05:03 UTC, AlmostEfficient requested changes

2022-01-31 05:03 UTC, AlmostEfficient commented on Solana_NFTs/en/Section_2/Lesson_2_Setup_NFT_Assets.md
> +**Making a small configuration!**
Can you remove this bit? I added this in https://github.com/buildspace/buildspace-projects/blob/main/Solana_NFTs/en/Section_2/Lesson_3_Depoy_NFTs_To_Devnet.md#configure-your-candy-machine

The rest looks good! I didn't update the JSON metadata because it wasn't explicitly necessary but I suppose it would help to keep it consistent with the docs.

2022-02-11 19:39 UTC, rodsemi commented on Solana_NFTs/en/Section_2/Lesson_2_Setup_NFT_Assets.md
> +**Making a small configuration!**
Omg sorry for the late reply! I believe I did what you asked. Sorry if I messed up first time doing this.

2022-02-16 14:30 UTC, adilanchian commented
@AlmostEfficient - feel free to merge in if you feel good about it!

2022-09-19 02:11 UTC, closed without merging