Update the link to metaplex candy machine src
buildspace/buildspace-projects pull request #814
Opened 2022-01-16 19:56 UTC by lightyaer

The old link results in 404, added url to file location.

2022-01-20 05:10 UTC, vishalkrv reviewed
Link is correct

2022-01-20 05:11 UTC, vishalkrv approved these changes

2022-01-31 04:34 UTC, AlmostEfficient requested changes
Looks like they changed it again! New link - https://github.com/metaplex-foundation/metaplex-program-library/blob/master/candy-machine/program/src/lib.rs

2022-04-01 21:58 UTC, lightyaer commented
This issue has already been resolved, oopsie I was too late for this.

2022-04-01 21:58 UTC, closed without merging