Translate to Portuguese the Solidity course - Section 2 - Lesson 4
buildspace/buildspace-projects pull request #817
Opened 2022-01-17 17:33 UTC by daniserafs

2022-01-18 12:43 UTC, izichtl commented on Solidity_And_Smart_Contracts/pt/Section_2/Lesson_1_Setup_React_App.md
> +🦊 Metamask
A linha 27 parece muito mais fechamento do primeiro bloco, do que abertura do segundo. Eu colocaria a linha 24 antes da 29.

2022-01-18 12:48 UTC, izichtl requested changes

2022-01-18 12:48 UTC, izichtl commented on Solidity_And_Smart_Contracts/pt/Section_2/Lesson_1_Setup_React_App.md
> +**Mas, nós precisamos de algo que conecte o nosso website com a nossa carteira para que nós possamos passar de forma segura as credenciais da dela para o nosso site, para que então ele possa usar ess
'credenciais da dela para o nosso site' precisaria remover o 'da'

Talvez usar 'credenciais salvas na carteira' reforce a ideia de onde vem a 'informação'.

2022-01-18 12:50 UTC, izichtl commented on Solidity_And_Smart_Contracts/pt/Section_2/Lesson_1_Setup_React_App.md
> +**Mas, nós precisamos de algo que conecte o nosso website com a nossa carteira para que nós possamos passar de forma segura as credenciais da dela para o nosso site, para que então ele possa usar ess
'credenciais da dela'

2022-01-18 14:23 UTC, daniserafs reviewed
I changed a few things that needed improvement

2022-12-16 15:49 UTC, helloitsm3 commented
Closing as we do not have any way to verify the contents at the moment. Do re-open if you feel that this needs another review.

2022-12-16 15:49 UTC, closed without merging