Improve explanation of pragma condition (^).
buildspace/buildspace-projects pull request #845
Opened 2022-01-24 02:05 UTC by sicongzhao

Modify the inaccurate explanation of pragma condition syntax (^).

2022-01-28 07:48 UTC, AlmostEfficient approved these changes

2022-01-28 07:52 UTC, AlmostEfficient commented
Would also help to link to the [relevant part in the docs](https://github.com/buildspace/buildspace-projects/pull/845/files#diff-89f165434c169942deca73439b3c6a3e4037fa7d89fb4b77da079cdad8999d60R47). What do you think @adilanchian?

2022-01-28 07:53 UTC, AlmostEfficient requested changes

2022-01-28 07:53 UTC, AlmostEfficient commented on NFT_Collection/en/Section_1/Lesson_3_Mint_A_NFT_Locally.md
> +This is the version of the Solidity compiler we want our contract to use. It basically says "when running this, I only want to use version no earlier than 0.8.0 but earlier than 0.9.0 of the Solidity
This could perhaps be changed to 

```
"when running this, I only want to use a version 0.8.0 or higher, but not higher than 0.9.0."
 ```

2022-01-28 07:54 UTC, AlmostEfficient commented on NFT_Collection/en/Section_1/Lesson_3_Mint_A_NFT_Locally.md
> +This is the version of the Solidity compiler we want our contract to use. It basically says "when running this, I only want to use version no earlier than 0.8.0 but earlier than 0.9.0 of the Solidity
Easier to understand for non-native speakers and closes the quote :)

Great catch btw!

2022-01-28 08:08 UTC, sicongzhao commented on NFT_Collection/en/Section_1/Lesson_3_Mint_A_NFT_Locally.md
> +This is the version of the Solidity compiler we want our contract to use. It basically says "when running this, I only want to use version no earlier than 0.8.0 but earlier than 0.9.0 of the Solidity
> This could perhaps be changed to
> 
> ```
> "when running this, I only want to use a version 0.8.0 or higher, but not higher than 0.9.0."
> ```

Yes, I agree. This is a better way to phrase it.

2022-02-04 09:15 UTC, AlmostEfficient approved these changes

2022-02-06 09:23 UTC, merged

2022-02-06 09:23 UTC, AlmostEfficient commented
@all-contributors please add @sicongzhao for documentation