update/remove undefined references
buildspace/buildspace-projects pull request #849
Opened 2022-01-24 21:56 UTC by WaterlessPiano2

Keeping these in the code were breaking it. making these changes have fixed it

2022-01-28 07:45 UTC, AlmostEfficient requested changes

2022-01-28 07:45 UTC, AlmostEfficient commented on Solana_NFTs/en/Section_4/Lesson_1_Drop_Timer_And_Sold_Out_State.md
> -            disabled={isMinting}
Could you put this back? We're using it at the moment.

2022-01-28 07:46 UTC, AlmostEfficient commented
The rest looks good to me! Thanks for the contribution!

2022-01-30 18:26 UTC, WaterlessPiano2 commented on Solana_NFTs/en/Section_4/Lesson_1_Drop_Timer_And_Sold_Out_State.md
> -            disabled={isMinting}
No :) because then I get the error `'isMinting' is not defined`. I haven't seen us define `isMInting` anywhere in the base repo, or on the tutorial.

2022-01-30 22:35 UTC, WaterlessPiano2 commented on Solana_NFTs/en/Section_4/Lesson_1_Drop_Timer_And_Sold_Out_State.md
> -            disabled={isMinting}
If you show me where isMinting gets defined I will remove these form the PR :+1:

2022-01-31 10:19 UTC, AlmostEfficient commented on Solana_NFTs/en/Section_4/Lesson_1_Drop_Timer_And_Sold_Out_State.md
> -            disabled={isMinting}
Ah, you're right! That section has been temporarily removed. Good catch!

2022-01-31 21:32 UTC, WaterlessPiano2 commented on Solana_NFTs/en/Section_4/Lesson_1_Drop_Timer_And_Sold_Out_State.md
> -            disabled={isMinting}
Exactly, this is not a permanent solution, I would like to create a state called 'isMinting' and set it to true or false in my next PR.

2022-02-03 18:59 UTC, WaterlessPiano2 commented
@AlmostEfficient lets :shipit: then :)

2022-02-04 09:15 UTC, AlmostEfficient approved these changes

2022-02-06 09:24 UTC, merged

2022-02-06 09:24 UTC, AlmostEfficient commented
@all-contributors please add @WaterlessPiano2 for documentation

2022-02-06 09:25 UTC, AlmostEfficient commented
@all-contributors please add @WaterlessPiano2  for documentation