Fix metaplex path
buildspace/buildspace-projects pull request #916
Opened 2022-02-18 10:09 UTC by jte0711

Fix #915

2022-02-19 10:09 UTC, AlmostEfficient requested changes
Hi, there's about 20 other instances of us using `metaplex-foundation` instead of `metaplex`. 

That is the original structure. Since it doesn't make a difference, let's change all relevant instances to `metaplex`. Please update the remaining ones. 

Note - there's a few links, pls don't change those, they will break

2022-02-20 05:29 UTC, jte0711 commented
Hi @AlmostEfficient , I changed all the local paths (excluding the URLs). Please check it again. Thanks

2022-02-20 20:10 UTC, AlmostEfficient approved these changes

2022-02-20 20:10 UTC, merged

2022-02-20 20:10 UTC, AlmostEfficient commented
Thank you! 

@all-contributors please add @jte0711 for documentation